server:
  port: 8080

spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8e106.p.ssafy.io:9306/hast?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: tyranno2106!
  # JPA for auto reload
  jpa:
    show-sql: false
    hibernate.ddl-auto: ${jpa.ddl.option}
#  sql:
#    init:
#      mode: ${sql.init.mode}
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG